allowBuilds:
  '@heroui/shared-utils': true
  '@parcel/watcher': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
packages:
  - apps/*
  - packages/*
pmOnFail: warn
