allowBuilds:
  '@heroui/shared-utils': true
  '@parcel/watcher': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
overrides:
  brace-expansion@1: ^1.1.21
  browserslist: ^4.29.3
  js-cookie: ^3.0.8
  lodash: ^4.18.1
  minimatch@3: ^3.1.5
  picomatch@2: ^2.3.2
  picomatch@4: ^4.0.7
packages:
  - apps/*
  - packages/*
patchedDependencies:
  vitest-fail-on-console@0.10.1: patches/vitest-fail-on-console@0.10.1.patch
pmOnFail: warn
