name: Pull request gated build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Initialize environment
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Compile Docker image
        run: pnpm docker:build
